sorts meetings in descending order of dates
t0xic0der/fragment pull request #28
Opened 2021-09-01 14:50 UTC by mugiwarafx

2021-09-02 02:07 UTC, t0xic0der requested changes
Could you also sort multiple meetings on the same day?

For instance,

![01](https://user-images.githubusercontent.com/49605954/131769790-42a7126f-7749-40de-b10d-af4cd59c90fa.png)

2021-09-02 02:07 UTC, t0xic0der commented on static/jscn/fragment.js
> +
Could you please do away with excess in-line spacings and set the indentation right?

2021-09-04 10:40 UTC, t0xic0der requested changes
Still not quite there - note the Fedora Project Management meetings in the attached screenshot. I see a 20:00 meeting getting listed after the one at 13:11 even though the former happened after the latter.

![01](https://user-images.githubusercontent.com/49605954/132091722-a9dc4a93-a38b-4783-82f3-5c97374fc164.png)

2021-09-04 14:02 UTC, mugiwarafx commented
Hi t0xic0der 🙂️

Seems like some kind of dark magic is going on here... Let me check my DADA book.

Just kidding! It looks like your browser is serving the old js file... could that be the case?

It is apparently working correctly on my machine:

![Screenshot from 2021-09-04 15-42-15](https://user-images.githubusercontent.com/58401248/132096523-38b7ed85-ed33-4f49-8038-05412c4cc703.png)

2021-09-04 14:48 UTC, t0xic0der commented
Yep, you are right.

After I spammed `Ctrl+Shift+R` multiple times, it loaded up the way it was supposed to.

![01](https://user-images.githubusercontent.com/49605954/132098519-75ec4173-c37d-4b13-b26e-d6d02b550129.png)

2021-09-04 14:50 UTC, t0xic0der commented
@thunderbirdtr @lilyx13 @nasirhm @ramyaparimi - Can I have a couple of +1s from your end too before I approve of this merge?

2021-09-07 03:55 UTC, t0xic0der approved these changes

2021-09-07 03:55 UTC, merged